from enum import Enum


class EstadoExpediente(str, Enum):
    BORRADOR = "BORRADOR"
    DOCUMENTACION_EN_CARGA = "DOCUMENTACION_EN_CARGA"
    PENDIENTE_VALIDACION = "PENDIENTE_VALIDACION"
    PENDIENTE_REVALIDACION = "PENDIENTE_REVALIDACION"
    VALIDADO = "VALIDADO"
    DISPOSICION_EMITIDA = "DISPOSICION_EMITIDA"
    FIRMADO = "FIRMADO"
    CERRADO = "CERRADO"
    DESISTIDO = "DESISTIDO"
    ARCHIVADO = "ARCHIVADO"
