from enum import StrEnum

from pydantic import BaseModel


class CodigoProximaAccionExpediente(StrEnum):
    COMPLETAR_PREPARACION = "COMPLETAR_PREPARACION"
    COMPLETAR_VALIDACION = "COMPLETAR_VALIDACION"
    REVALIDAR_EXPEDIENTE = "REVALIDAR_EXPEDIENTE"
    INCORPORAR_OP = "INCORPORAR_OP"
    SELECCIONAR_PROVEEDOR = "SELECCIONAR_PROVEEDOR"
    CONTROLAR_PROVEEDOR = "CONTROLAR_PROVEEDOR"
    REGULARIZAR_PROVEEDOR = "REGULARIZAR_PROVEEDOR"
    REVISAR_DOCUMENTACION_OP = "REVISAR_DOCUMENTACION_OP"
    PREPARAR_DISPOSICION = "PREPARAR_DISPOSICION"
    REGISTRAR_FORMALIZACION = "REGISTRAR_FORMALIZACION"
    CERRAR_EXPEDIENTE = "CERRAR_EXPEDIENTE"
    REGISTRAR_FIRMA_LEGACY = "REGISTRAR_FIRMA_LEGACY"
    ARCHIVAR_EXPEDIENTE = "ARCHIVAR_EXPEDIENTE"
    CONSULTAR_HISTORIAL = "CONSULTAR_HISTORIAL"


class ProximaAccionExpedienteRead(BaseModel):
    expediente_id: str
    codigo: CodigoProximaAccionExpediente
    etiqueta: str
    descripcion: str
    prioridad: int
    documento_op_id: str | None = None
    circuito_legacy: bool = False
